name: news_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  pdf: ^3.10.7
  printing: ^5.12.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  url_launcher: ^6.0.9
  connectivity_plus: ^2.3.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  provider: ^6.0.4
  webview_flutter: 4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  mobx_codegen: ^2.0.0

flutter:
  uses-material-design: true